apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: next-app-run-
spec:
  pipelineRef:
    name: next-app
  params:
    - name: app-name
      value: next-app
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/asaa-john-next-app/tree/main/tekton-e2e-assignment
    - name: image-repo
      value: quay.io/john_sourg/next-app
  serviceAccountName: build-bot
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi