apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: vcs-trigger
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: express-sample-app-pipeline-
      spec:
        pipelineRef:
          name: nodejs-pipeline
        serviceAccountName: build-bot
        params:
          - name: app-name
            value: express-sample-app
          - name: source-repo
            value: $(tt.params.source-repo)  
          - name: sha                        
            value: $(tt.params.sha)
          - name: image-repo
            value: quay.io/asaaumar/express-sample-app
        workspaces:
          - name: pipeline-shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi